//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

public class Board
{
	public virtual IEnumerable<Field> Field
	{
		get;
		set;
	}

	public virtual Town Town
	{
		get;
		set;
	}

	public virtual ForestField ForestField
	{
		get;
		set;
	}

	public virtual IEnumerable<Barricade> Barricade
	{
		get;
		set;
	}

	public virtual IEnumerable<RedPion> RedPion
	{
		get;
		set;
	}

	public virtual IEnumerable<GreenPion> GreenPion
	{
		get;
		set;
	}

	public virtual IEnumerable<YellowPion> YellowPion
	{
		get;
		set;
	}

	public virtual IEnumerable<BluePion> BluePion
	{
		get;
		set;
	}

}

