//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

public abstract class Pion
{
    private Field _field;

    public Field Field
    {
        get;
        set;
    }

    public void SetField(Field field)
    {
        Field = field;
        Field.Pion = this;
    }
}

