//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

public abstract class Pion
{
    private Field _field;
    private char _letter;
    private ConsoleColor _cColor;
    private ConsoleColor _fColor;

    public Field Field
    {
        get;
        set;
    }
    public Char Letter
    {
        get
        {
            return _letter;
        }
        set
        {
            _letter = value;
        }
    }
    public ConsoleColor CColor
    {
        get
        {
            return _cColor;
        }
        set
        {
            _cColor = value;
        }
    }

    public void SetField(Field field)
    {
        Field = field;
        Field.Pion = this;
    }
}

